.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamic window manager
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
dwm is a dynamic window manager for X. It manages windows in tiled, monocle
and floating layouts. Either layout can be applied dynamically, optimising the
environment for the application in use and the task performed.
.P
In tiled layouts windows are managed in a master and stacking area. The master
area on the left contains one window by default, and the stacking area on the
right contains all other windows. The number of master area windows can be
adjusted from zero to an arbitrary number. In monocle layout all windows are
maximised to the screen size. In floating layout windows can be resized and
moved freely. Dialog windows are always managed floating, regardless of the
layout applied.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags.
.P
dwm draws a small border around windows to indicate the focus state.
.SH OPTIONS
.TP
.B \-v
prints version information to stderr, then exits.
.SH USAGE
.SS Keyboard commands
.TP
.B Super\-space
Start
.BR st(1).
.TP
.B Super\-d
Spawn
.BR dmenu(1)
for launching other programs.
.TP
.B Alt\-space
Start
.BR st(1)
in a floating window.
.TP
.B Super\-,
Focus previous screen, if any.
.TP
.B Super\-.
Focus next screen, if any.
.TP
.B Super\-Shift\-,
Send focused window to previous screen, if any.
.TP
.B Super\-Shift\-.
Send focused window to next screen, if any.
.TP
.B Super\-o
Toggles mouse on and off.
.TP
.B Super\-p
Spawn dmenu to search through open windows on non-visible tags and move to the tag
which the selected window is on.
.TP
.B Super\-Shift\-p
Spawn dmenu to search through open windows on non-visible tags and send them to 
currently active tag.
.TP
.B Super\-Shift\-q
Spawn dmenu to search through open windows on non-visible tags and kill selected
window
.TP
.B Super\-t
Sets tiled layout.
.TP
.B Super\-f
Sets floating layout.
.TP
.B Super\-m
Sets monocle layout.
.TP
.B Super\-j
Focus next window.
.TP
.B Super\-k
Focus previous window.
.TP
.B Super\-minus
Increase number of windows in master area.
.TP
.B Super\-equals
Decrease number of windows in master area.
.TP
.B Super\-l
Increase master area size.
.TP
.B Super\-h
Decrease master area size.
.TP
.B Alt\-Tab
Zooms/cycles focused window to/from master area (tiled layouts only).
.TP
.B Super\-q
Close focused window.
.TP
.B Super\-Return
Toggle floating for focused window.
.TP
.B Super\-Shift\-Return
Toggle fullscreen for focused window.
.TP
.B Super\-Tab
Toggles to the previously selected tag.
.TP
.B Super\-Shift\-[1..n]
Apply nth tag to focused window.
.TP
.B Super\-Shift\-grave
Apply all tags to focused window.
.TP
.B Super\-Control\-Shift\-[1..n]
Add/remove nth tag to/from focused window.
.TP
.B Super\-[1..n]
View all windows with nth tag.
.TP
.B Super\-grave
View all windows with any tag.
.TP
.B Super\-Control\-[1..n]
Add/remove all windows with nth tag to/from the view.
.TP
.B Super\-Control\-Shift\-BackSpace
Quit dwm.
.TP
.B Super\-Shift\-r
Restart dwm.
.TP
.B Super\-n
Launch newsboat RSS reader in an
.BR st(1)
window.
.TP
.B Super\-Escape
Launch htop in an
.BR st(1)
window.
.TP
.B Alt\-Escape
Launch htop in a floating
.BR st(1)
window.
.TP
.B Super\-x
Run xkill to kill an X window.
.TP
.B Super\-w
Launch web browser.
.TP
.B Super\-Shift\-w
Launch alternate web browser.
.TP
.B Super\-a
Swap focus between last focused window.
.TP
.B Super\-PrintScreen
Screenshot


.SS Moving floating windows
.TP
.B Rightmost 'wasd' like cluster of keys in GB ISO keyboard layout
 
.TP
.B Super\-apostrophe
Move focused floating window down
.TP
.B Super\-bracketleft
Move focused floating window up
.TP
.B Super\-hash
Move focused floating window right
.TP
.B Super\-semicolon
Move focused floating window left

.SS Resizing floating windows
.TP
.B Rightmost 'wasd' like cluster of keys in GB ISO keyboard layout

.TP
.B Super\-Shift\-apostrophe
Resize focused floating window down
.TP
.B Super\-Shift\-bracketleft
Resize focused floating window up
.TP
.B Super\-Shift\-hash
Resize focused floating window right
.TP
.B Super\-Shift\-semicolon
Resize focused floating window left


.SS Mouse commands
.TP
.B Super\-LMB
Tiled windows will be swapped through the positions of other tiled windows. Floating windows will be moved as normal
.TP
.B Super\-Shift\-LMB
Move focused window while dragging. Tiled windows will be toggled to the floating state.
.TP
.B Super\-MMB
Toggles focused window between floating and tiled state.
.TP
.B Super\-RMB
Tiled windows will have the area they are occupying in the layout resized, while floating windows will be resized normally
.TP
.B Super\-ScrollWheelDown
Focus next window.
.TP
.B Super\-ScrollWheelUp
Focus previous window.
.TP
.B Super\-Button8 (Side mouse button)
Focus previous screen, if any.
.TP
.B Super\-Button9 (Side mouse button)
Focus next screen, if any.
.SH CUSTOMIZATION
dwm is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SIGNALS
.TP
.B SIGHUP - 1
Restart the dwm process.
.TP
.B SIGTERM - 15
Cleanly terminate the dwm process.
.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
.SH ISSUES
Java applications which use the XToolkit/XAWT backend may draw grey windows
only. The XToolkit/XAWT backend breaks ICCCM-compliance in recent JDK 1.5 and early
JDK 1.6 versions, because it assumes a reparenting window manager. Possible workarounds
are using JDK 1.4 (which doesn't contain the XToolkit/XAWT backend) or setting the
environment variable
.BR AWT_TOOLKIT=MToolkit
(to use the older Motif backend instead) or running
.B xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
or
.B wmname LG3D
(to pretend that a non-reparenting window manager is running that the
XToolkit/XAWT backend can recognize) or when using OpenJDK setting the environment variable
.BR _JAVA_AWT_WM_NONREPARENTING=1 .
.SH BUGS
Send all bug reports with a patch to hackers@suckless.org.
